version: '3.8'
name: "tpx-app"
services:
  nginx:
    image: nginx:latest
    container_name: tpx_nginx_cont
    ports:
      - "7800:7800"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
  db:
    image: postgres:14.1
    container_name: tpx_db_cont
    restart: no
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - db
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    env_file:
      - project.env

  frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    image: frontend
    restart: no
    container_name: tpx_frontend_cont
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173
    env_file:
      - project.env

  backend:
    build:
     context: ./backend
     dockerfile: Dockerfile
    image: backend
    restart: no
    container_name: tpx_backend_cont
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
        - 8080
    env_file:
      - project.env


volumes:
  db_data:
  node_modules:
