version: '3.8'
name: "tpx-app"
services:
  nginx:
    image: nginx:latest
    container_name: tpx_nginx_cont
    ports:
      - "7800:7800"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  db:
    image: postgres:14.1
    container_name: tpx_db_cont
    restart: no
    env_file:
      - project.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      db:
        condition: service_healthy
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    env_file:
      - project.env

  frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    image: frontend
    restart: no
    container_name: tpx_frontend_cont
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173
    env_file:
      - project.env

  backend:
    build:
     context: ./backend
     dockerfile: Dockerfile
    image: backend
    restart: no
    container_name: tpx_backend_cont
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
        - 8080
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      
    env_file:
      - project.env
      - ./backend/.env


volumes:
  db_data:
  node_modules:
